### ISSUE TITLE
Use decimal for payment amounts

### ISSUE THREAD

**Issue by michaelaird** [Beanstream/beanstream-dotnet#12]
Using a double (floating point type) can lead to dangerous rounding errors. Use decimal instead.

https://www.noelherrick.com/blog/always-use-decimal-for-money

**Comment by bowens-bambora** [comment]
PR #13 merged and committed. New release and tag v1.2.0 released to nuget

**Comment by michaelaird** [comment]
As a follow up on this, here's why to use decimal here instead of double:

[Decimal vs Double and Other Tips About Number Types in .NET](https://www.exceptionnotfound.net/decimal-vs-double-and-other-tips-about-number-types-in-net/)

tl;dr precision over performance.
