### ISSUE TITLE
Address optional when creating new Profile

### ISSUE THREAD

**Issue by tutkoo** [Beanstream/beanstream-dotnet#6]
I was going through the CreateProfile documentation and Address is mostly optional http://support.beanstream.com/restapi/#!/Profiles/post_profiles The API forces to provide address and performs a null check on all the fields.

I was wondering is address necessary?

**Comment by BeanstreamDeveloper** [comment]
Good call, it's not actually required so the API should not perform the check. I removed it and pushed the change to commit [04fc748](https://github.com/Beanstream-DRWP/beanstream-dotnet/commit/ffe9c49e8f8ff36772ccbbc9893231fd5889d2f1)

**Comment by tutkoo** [comment]
Thank you very much.
