### ISSUE TITLE
Latest changes not available in the nuget package

### ISSUE THREAD

**Issue by tutkoo** [Beanstream/beanstream-dotnet#7]
Hello,

I can see the recent changes in code, like adding Card to Payment Profile by using token; but somehow hasn't shown in the latest Nuget package.

Is there something needs to be done on our end to get those changes through Nuget?
<img width="736" alt="addcard" src="https://cloud.githubusercontent.com/assets/5695598/9369644/69ae3f06-467f-11e5-842c-b064aa2e4c95.PNG">

**Comment by BeanstreamDeveloper** [comment]
Hmm, okay I will take a look. Realistically I will be able to push up a new Nuget package tomorrow morning. I will let you know as soon as it is up.

**Comment by tutkoo** [comment]
Thank you no rush.

**Comment by sploreg** [comment]
A new package has been deployed and I confirmed that the methods for adding a Token to a Profile is there.
Version number is [1.0.0-rc4](https://www.nuget.org/packages/Beanstream/1.0.0-rc4)

**Comment by tutkoo** [comment]
I verified it as well and can see the changes. Thank you.
