### ISSUE TITLE
HttpWebRequest.cs content-type type for json code-block

### ISSUE THREAD

**Issue by hrmilo** [Beanstream/beanstream-dotnet#8]
Line 111: There exists a semi-colon just after the Console.WriteLine separating what seems to be the intended code-block for the conditional, but in fact is just a stand-alone code block.....Was this intentional?  Was the Console.WriteLine supposed to have been removed after some debugging had been performed?

Also, if I remove the semi-colon, I then have to change the response.ContentType.Equals("application/json") to response.ContentType.Contains("application/json") due to some servers returning  content-type of "application/json; charset=utf-8"

Thanks for the effort!

**Comment by bowens-bambora** [comment]
Thanks @hrmilo. I've removed that writeline and changed the .equals to .contains. The change has been pushed.

Cheers,
